<main>
       <!-- Affichage du template lié à la vue -->
       <h2><i class="fa fa-star"></i> Commande payée</h2>

<h3>Merci d'avoir commandé au 3WA Restaurant !</h3>

<p data-order-step="success">Votre commande numéro <?= $_GET['orderId']?> a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
<p class="layout-center"><img alt="Commande payée" src="<?= $wwwUrl ?>/images/success.gif"></p>

<a class="button button-primary" href="<?= $requestUrl ?>">Accueil</a>


<!-- Classes de gestion du formulaire de commande -->
<!-- Ce code JavaScript n'est chargé QUE depuis l'URL /order/payment/success -->
<script type="text/javascript">

	window.localStorage.removeItem('panier');

</script>

<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/Commande.class.js"></script>  </main>
