<form class="" action="register.php" method="post">
  <fieldset>
    <legend>S'inscrire</legend>
    <label>Nom</label>
    <input type="text" name="firstName" placeholder="entrez votre nom">
    <label>Prénom</label>
    <input type="text" name="lastName"  placeholder="entrez votre prénom">
    <label>Email</label>
    <input type="email" name="mail" placeholder="entrez votre email">
    <label>Mot de passe</label>
    <input type="text" name="password" placeholder="entrez votre mot de passe">
    <input type="submit" name="valider" value="Valider">
  </fieldset>

  <p>Déjà inscrit ? <a href='login.php'>connectez-vous !</a></p>

</form>
