<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <a href="index.php">Accueil</a>

    <?php if (array_key_exists('user', $_SESSION) == false) {?>

    <form id="login-form" action="login.php" method="POST">
    	<label>Email</label>
    	<input type="text" name="mail" />

        <label>Password</label>
    	<input type="password" name="password" />

    	<input type="submit" value="envoyer" />
    </form>

    <?php } else {?>

    <p>Vous êtes connecté</p>
    <a href="logout.php">logout</a>

    <?php } ?>


    </form>
  </body>
</html>
