<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <a href="index.php">Acceuil</a>
    <form action="register.php" method="post">
      <label>Nom</label>
      <input type="text" name="firstName">
      <label>Prénom</label>
      <input type="text" name="lastName">
      <label>Email</label>
      <input type="email" name="mail">
      <label>Password</label>
      <input type="text" name="password">
      <input type="submit" name="submit" value="Envoyer">

    </form>
  </body>
</html>
